# Generated by Django 5.2.3 on 2025-06-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={},
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='views',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='advertisements/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='AdvertisementImage',
        ),
    ]
