# Generated by Django 5.2.3 on 2025-08-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='url',
            new_name='external_link',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/'),
        ),
    ]
