# Generated by Django 5.2.3 on 2025-08-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_rename_url_advertisement_external_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='target',
            new_name='target_user',
        ),
    ]
