# Generated by Django 5.2.3 on 2025-09-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0013_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='farm_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
