# Generated by Django 5.2.3 on 2025-08-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkhistory', '0003_milkhistory_farm_alter_milkhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkhistory',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measurement for volumes and weights (e.g., liters, pounds)', max_length=100, null=True),
        ),
    ]
