# Generated by Django 5.2.3 on 2025-08-27 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkhistory', '0005_alter_milkhistory_farm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkhistory',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='The farm associated with this milk preparation record', limit_choices_to={'role': 'farm'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_milk_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
